title: OmniSocial ProtocolKit
description: "A modular starter kit for federated, decentralized social apps."
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: default
search: true
markdown: kramdown
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: UTC

include:
  - _pages

collections:
  pages:
    output: true
    permalink: /:path/

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
